src/Presentation/SmartStore.Web/Models/Catalog/BackInStockSubscribeModel.cs
using SmartStore.Services.Localization;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Catalog
{
    public partial class BackInStockSubscribeModel : ModelBase
    {
        public int ProductId { get; set; }
        public LocalizedValue<string> ProductName { get; set; }
        public string ProductSeName { get; set; }

        public bool IsCurrentCustomerRegistered { get; set; }
        public bool SubscriptionAllowed { get; set; }
        public bool AlreadySubscribed { get; set; }

        public int MaximumBackInStockSubscriptions { get; set; }
        public int CurrentNumberOfBackInStockSubscriptions { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Catalog/CategoryModel.cs
using System.Collections.Generic;
using SmartStore.Core.Domain.Catalog;
using SmartStore.Services.Localization;
using SmartStore.Services.Search;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Framework.UI;
using SmartStore.Web.Models.Media;
using SmartStore.Web.Models.Search;

namespace SmartStore.Web.Models.Catalog
{
    public partial class CategorySummaryModel : EntityModelBase
    {
        public LocalizedValue<string> Name { get; set; }
        public string Url { get; set; }
        public PictureModel PictureModel { get; set; } = new PictureModel();

        // TODO: Badges
    }

    public partial class CategoryModel : EntityModelBase, ISearchResultModel
    {
        public CategoryModel()
        {
			PictureModel = new PictureModel();
            SubCategories = new List<CategorySummaryModel>();
        }

		public CatalogSearchResult SearchResult
		{
			get;
			set;
		}

		public LocalizedValue<string> Name { get; set; }
		public LocalizedValue<string> FullName { get; set; }
        public LocalizedValue<string> Description { get; set; }
		public LocalizedValue<string> BottomDescription { get; set; }
        public LocalizedValue<string> MetaKeywords { get; set; }
        public LocalizedValue<string> MetaDescription { get; set; }
        public LocalizedValue<string> MetaTitle { get; set; }
        public string SeName { get; set; }

        public PictureModel PictureModel { get; set; }

        public bool DisplayCategoryBreadcrumb { get; set; }

		public SubCategoryDisplayType SubCategoryDisplayType { get; set; }
        public IList<CategorySummaryModel> SubCategories { get; set; }

        public ProductSummaryModel FeaturedProducts { get; set; }
        public ProductSummaryModel Products { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Catalog/IListActions.cs
using System.Collections.Generic;
using SmartStore.Core;
using SmartStore.Core.Domain.Catalog;

namespace SmartStore.Web.Models.Catalog
{
    public interface IListActions
	{
		ProductSummaryViewMode ViewMode { get; }
		GridColumnSpan GridColumnSpan { get; }
		bool AllowViewModeChanging { get; }

		bool AllowFiltering { get; }

		bool AllowSorting { get; }
		int? CurrentSortOrder { get; }
		string CurrentSortOrderName { get; }
        string RelevanceSortOrderName { get; }
        IDictionary<int, string> AvailableSortOptions { get; }

        IPageable PagedList { get; }
        IEnumerable<int> AvailablePageSizes { get; }
    }
}

src/Presentation/SmartStore.Web/Models/Catalog/IQuantityInput.cs
using SmartStore.Core.Domain.Catalog;
using SmartStore.Services.Localization;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace SmartStore.Web.Models.Catalog
{
	public interface IQuantityInput
	{
		int EnteredQuantity { get; }
		int MinOrderAmount { get; }
		int MaxOrderAmount { get; }
        int QuantityStep { get; }
		LocalizedValue<string> QuantityUnitName { get; }
		List<SelectListItem> AllowedQuantities { get; }
        QuantityControlType QuantiyControlType { get; }
    }
}

src/Presentation/SmartStore.Web/Models/Catalog/ManufacturerModel.cs
using System.Collections.Generic;
using SmartStore.Services.Localization;
using SmartStore.Services.Search;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Models.Media;
using SmartStore.Web.Models.Search;

namespace SmartStore.Web.Models.Catalog
{
    public partial class ManufacturerModel : EntityModelBase, ISearchResultModel
	{
        public ManufacturerModel()
        {
            PictureModel = new PictureModel();
        }

        public LocalizedValue<string> Name { get; set; }
        public LocalizedValue<string> Description { get; set; }
        public LocalizedValue<string> MetaKeywords { get; set; }
        public LocalizedValue<string> MetaDescription { get; set; }
        public LocalizedValue<string> MetaTitle { get; set; }
        public string SeName { get; set; }

        public PictureModel PictureModel { get; set; }
        public ProductSummaryModel FeaturedProducts { get; set; }
        public ProductSummaryModel Products { get; set; }

		public CatalogSearchResult SearchResult
		{
			get;
			set;
		}
	}
}

src/Presentation/SmartStore.Web/Models/Catalog/ManufacturerNavigationModel.cs
using System.Collections.Generic;
using SmartStore.Services.Localization;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Catalog
{
    public partial class ManufacturerNavigationModel : ModelBase
    {
        public ManufacturerNavigationModel()
        {
            this.Manufacturers = new List<ManufacturerBriefInfoModel>();
        }

        public IList<ManufacturerBriefInfoModel> Manufacturers { get; set; }
        
        public bool DisplayAllManufacturersLink { get; set; }

        public bool DisplayManufacturers { get; set; }

        public bool DisplayImages { get; set; }
    }

    public partial class ManufacturerBriefInfoModel : EntityModelBase
    {
        public LocalizedValue<string> Name { get; set; }

        public string SeName { get; set; }

        public string PictureUrl { get; set; }

		public int? PictureId { get; set; }

		public bool HasPicture { get; set; }

        public int DisplayOrder { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Catalog/ManufacturerOverviewModel.cs
using SmartStore.Services.Localization;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Models.Media;

namespace SmartStore.Web.Models.Catalog
{
    public partial class ManufacturerOverviewModel : EntityModelBase
    {
        public LocalizedValue<string> Name { get; set; }
        public LocalizedValue<string> Description { get; set; }
		public string SeName { get; set; }
		public PictureModel Picture { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Catalog/ProductSpecificationModel.cs
using SmartStore.Services.Localization;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Catalog
{
    public partial class ProductSpecificationModel : ModelBase
    {
        public int SpecificationAttributeId { get; set; }
        public LocalizedValue<string> SpecificationAttributeName { get; set; }
        public LocalizedValue<string> SpecificationAttributeOption { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Catalog/ProductTagModel.cs
using SmartStore.Services.Localization;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Catalog
{
    public partial class ProductTagModel : EntityModelBase
    {
        public LocalizedValue<string> Name { get; set; }

        public string SeName { get; set; }

        public int ProductCount { get; set; }
    }
}

src/Presentation/SmartStore.Web/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel.Syndication;
using System.Web.Mvc;
using SmartStore.Core.Caching;
using SmartStore.Core.Domain.Catalog;
using SmartStore.Core.Domain.Customers;
using SmartStore.Core.Domain.Media;
using SmartStore.Services;
using SmartStore.Services.Catalog;
using SmartStore.Services.Common;
using SmartStore.Services.Localization;
using SmartStore.Services.Media;
using SmartStore.Services.Orders;
using SmartStore.Services.Search;
using SmartStore.Services.Security;
using SmartStore.Services.Seo;
using SmartStore.Services.Stores;
using SmartStore.Utilities;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.Filters;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Framework.Security;
using SmartStore.Web.Framework.UI;
using SmartStore.Web.Infrastructure.Cache;
using SmartStore.Web.Models.Catalog;
using SmartStore.Web.Models.Media;

namespace SmartStore.Web.Controllers
{
    public partial class CatalogController : PublicControllerBase
    {
		private readonly ICommonServices _services;
        private readonly IMenuService _menuService;
        private readonly ICategoryService _categoryService;
        private readonly IManufacturerService _manufacturerService;
        private readonly IProductService _productService;
        private readonly ICategoryTemplateService _categoryTemplateService;
        private readonly IManufacturerTemplateService _manufacturerTemplateService;
        private readonly IPictureService _pictureService;
		private readonly IOrderReportService _orderReportService;
		private readonly IProductTagService _productTagService;
		private readonly IRecentlyViewedProductsService _recentlyViewedProductsService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly IAclService _aclService;
		private readonly IStoreMappingService _storeMappingService;
		private readonly ICatalogSearchService _catalogSearchService;
		private readonly MediaSettings _mediaSettings;
        private readonly CatalogSettings _catalogSettings;
		private readonly ICompareProductsService _compareProductsService;
        private readonly CatalogHelper _helper;
		private readonly IBreadcrumb _breadcrumb;

		public CatalogController(
			ICommonServices services,
            IMenuService menuService,
            ICategoryService categoryService,
            IManufacturerService manufacturerService, 
			IProductService productService,
            ICategoryTemplateService categoryTemplateService,
            IManufacturerTemplateService manufacturerTemplateService,
			IOrderReportService orderReportService,
			IProductTagService productTagService,
			IRecentlyViewedProductsService recentlyViewedProductsService,
            IPictureService pictureService,
			ICompareProductsService compareProductsService,
			IGenericAttributeService genericAttributeService,
			IAclService aclService,
			IStoreMappingService storeMappingService,
			ICatalogSearchService catalogSearchService,
			MediaSettings mediaSettings, 
			CatalogSettings catalogSettings,
            CatalogHelper helper,
			IBreadcrumb breadcrumb)
        {
			_services = services;
            _menuService = menuService;
			_categoryService = categoryService;
            _manufacturerService = manufacturerService;
            _productService = productService;
            _categoryTemplateService = categoryTemplateService;
            _manufacturerTemplateService = manufacturerTemplateService;
			_orderReportService = orderReportService;
			_productTagService = productTagService;
			_recentlyViewedProductsService = recentlyViewedProductsService;
			_compareProductsService = compareProductsService;
            _pictureService = pictureService;
            _genericAttributeService = genericAttributeService;
            _aclService = aclService;
			_storeMappingService = storeMappingService;
			_catalogSearchService = catalogSearchService;
            _mediaSettings = mediaSettings;
            _catalogSettings = catalogSettings;
            _helper = helper;
			_breadcrumb = breadcrumb;
        }

        #region Categories

        [RewriteUrl(SslRequirement.No)]
        public ActionResult Category(int categoryId, CatalogSearchQuery query)
        {
			var category = _categoryService.GetCategoryById(categoryId);
            if (category == null || category.Deleted)
				return HttpNotFound();

            // Check whether the current user has a "Manage catalog" permission.
            // It allows him to preview a category before publishing.
            if (!category.Published && !_services.Permissions.Authorize(StandardPermissionProvider.ManageCatalog))
				return HttpNotFound();

            // ACL (access control list).
            if (!_aclService.Authorize(category))
				return HttpNotFound();

			// Store mapping.
			if (!_storeMappingService.Authorize(category))
				return HttpNotFound();

            var store = _services.StoreContext.CurrentStore;
            var customer = _services.WorkContext.CurrentCustomer;

            // 'Continue shopping' URL.
            if (!_services.WorkContext.CurrentCustomer.IsSystemAccount)
			{
				_genericAttributeService.SaveAttribute(customer, SystemCustomerAttributeNames.LastContinueShoppingPage,	_services.WebHelper.GetThisPageUrl(false), store.Id);
			}

            var model = category.ToModel();
			if (query.IsSubPage && !_catalogSettings.ShowDescriptionInSubPages)
			{
				model.Description.ChangeValue(string.Empty);
			}

			_services.DisplayControl.Announce(category);

            // Category breadcrumb.
			if (_catalogSettings.CategoryBreadcrumbEnabled)
			{
                _helper.GetCategoryBreadcrumb(_breadcrumb, ControllerContext);
			}

			// Products.
			var catIds = new int[] { categoryId };
			if (_catalogSettings.ShowProductsFromSubcategories)
			{
				// Include subcategories.
				catIds = catIds.Concat(_helper.GetChildCategoryIds(categoryId)).ToArray();
			}

			query.WithCategoryIds(_catalogSettings.IncludeFeaturedProductsInNormalLists ? (bool?)null : false, catIds);

			var searchResult = _catalogSearchService.Search(query);
			model.SearchResult = searchResult;

			var mappingSettings = _helper.GetBestFitProductSummaryMappingSettings(query.GetViewMode());
			model.Products = _helper.MapProductSummaryModel(searchResult.Hits, mappingSettings);

			model.SubCategoryDisplayType = _catalogSettings.SubCategoryDisplayType;

			var customerRolesIds = customer.CustomerRoles.Where(x => x.Active).Select(x => x.Id).ToList();
			var pictureSize = _mediaSettings.CategoryThumbPictureSize;
			var fallbackType = _catalogSettings.HideCategoryDefaultPictures ? FallbackPictureType.NoFallback : FallbackPictureType.Entity;

			var hideSubCategories = _catalogSettings.SubCategoryDisplayType == SubCategoryDisplayType.Hide 
				|| (_catalogSettings.SubCategoryDisplayType == SubCategoryDisplayType.AboveProductList && query.IsSubPage && !_catalogSettings.ShowSubCategoriesInSubPages);
			var hideFeaturedProducts = _catalogSettings.IgnoreFeaturedProducts || (query.IsSubPage && !_catalogSettings.IncludeFeaturedProductsInSubPages);

			// Subcategories.
			if (!hideSubCategories)
			{
				var subCategories = _categoryService.GetAllCategoriesByParentCategoryId(categoryId);
                model.SubCategories = _helper.MapCategorySummaryModel(subCategories, pictureSize);
			}

			// Featured Products.
			if (!hideFeaturedProducts)
			{
				CatalogSearchResult featuredProductsResult = null;

				string cacheKey = ModelCacheEventConsumer.CATEGORY_HAS_FEATURED_PRODUCTS_KEY.FormatInvariant(categoryId, string.Join(",", customerRolesIds), store.Id);
				var hasFeaturedProductsCache = _services.Cache.Get<bool?>(cacheKey);

				var featuredProductsQuery = new CatalogSearchQuery()
					.VisibleOnly(customer)
					.VisibleIndividuallyOnly(true)
					.WithCategoryIds(true, categoryId)
					.HasStoreId(_services.StoreContext.CurrentStore.Id)
					.WithLanguage(_services.WorkContext.WorkingLanguage)
					.WithCurrency(_services.WorkContext.WorkingCurrency);

				if (!hasFeaturedProductsCache.HasValue)
				{
					featuredProductsResult = _catalogSearchService.Search(featuredProductsQuery);
					hasFeaturedProductsCache = featuredProductsResult.TotalHitsCount > 0;
					_services.Cache.Put(cacheKey, hasFeaturedProductsCache, TimeSpan.FromHours(6));
				}

				if (hasFeaturedProductsCache.Value && featuredProductsResult == null)
				{
					featuredProductsResult = _catalogSearchService.Search(featuredProductsQuery);
				}

				if (featuredProductsResult != null)
				{
					var featuredProductsmappingSettings = _helper.GetBestFitProductSummaryMappingSettings(ProductSummaryViewMode.Grid);
					model.FeaturedProducts = _helper.MapProductSummaryModel(featuredProductsResult.Hits, featuredProductsmappingSettings);
				}
			}

			// Prepare paging/sorting/mode stuff.
			_helper.MapListActions(model.Products, category, _catalogSettings.DefaultPageSizeOptions);

			// Template.
			var templateCacheKey = string.Format(ModelCacheEventConsumer.CATEGORY_TEMPLATE_MODEL_KEY, category.CategoryTemplateId);
			var templateViewPath = _services.Cache.Get(templateCacheKey, () =>
			{
				var template = _categoryTemplateService.GetCategoryTemplateById(category.CategoryTemplateId);
				if (template == null)
					template = _categoryTemplateService.GetAllCategoryTemplates().FirstOrDefault();
				return template.ViewPath;
			});

			// Activity log.
			_services.CustomerActivity.InsertActivity("PublicStore.ViewCategory", T("ActivityLog.PublicStore.ViewCategory"), category.Name);

			return View(templateViewPath, model);
		}

        [ChildActionOnly]
        public ActionResult HomepageCategories()
        {
			var categories = _categoryService.GetAllCategoriesDisplayedOnHomePage()
				.Where(c => _aclService.Authorize(c) && _storeMappingService.Authorize(c))
				.ToList();

src/Presentation/SmartStore.Web/Views/Catalog/Partials/HomepageBestSellers.cshtml
@model ProductSummaryModel

@using SmartStore.Web.Models.Catalog;

@{ 
	if (Model.Items.Count == 0)
	{
		return;
	}
}

<div class="product-grid bestsellers block">
	<div class="heading heading-center">
		<h3 class="heading-title fs-h1">@T("Bestsellers")</h3>
	</div>
    <div class="block-body pt-3 artlist-no-separators">
		@{
			Html.RenderPartial("Product.List", Model);
		}
    </div>
</div>

src/Presentation/SmartStore.Web/Views/Catalog/Partials/HomepageCategories.cshtml
@model IList<CategorySummaryModel>

@using SmartStore.Web.Models.Catalog;

@{ 
	if (Model.Count == 0)
	{
		return;
	}
}

<div class="artlist artlist-grid artlist-6-cols artlist-boxed artlist-homepage-categories">
	@foreach (var item in Model)
	{
		var picture = item.PictureModel;
		<article class="art" data-id="@item.Id">
			<div class="art-picture-block">
				@if (picture != null && picture.ImageUrl.HasValue())
				{
					<a class="art-picture img-center-container" href="@item.Url" title="@picture.Title">
						<img src="@picture.ImageUrl" alt="@picture.AlternateText" />
					</a>
				}
			</div>
			<div class="art-genericname">
				<a href="@item.Url" title="@item.Name">
					<span @Html.LanguageAttributes(item.Name)>@item.Name</span>
				</a>
			</div>
		</article>
	}
</div>

src/Presentation/SmartStore.Web/Views/Catalog/Partials/HomepageManufacturers.cshtml
@model ManufacturerNavigationModel
@using SmartStore.Web.Models.Catalog;

<div class="manufacturer-grid block">
    <div class="heading heading-center">
        <h3 class="heading-title fs-h1">@T("Homepage.TopBrands")</h3>
    </div>

    <div class="artlist artlist-grid artlist-6-cols artlist-boxed block-body pt-3">
        @foreach (var manufacturer in Model.Manufacturers)
        {
            @RenderManufacturer(manufacturer);
        }

		@if (Model.DisplayAllManufacturersLink)
		{
			<div class="art show-all-items d-flex p-0">
				<a href="@Url.RouteUrl("ManufacturerList")" class="show-all-items-link">
					<i class="fa fa-ellipsis-h fa-lg"></i>
					<span>@T("Homepage.Brands.ShowAll")</span>
				</a>
			</div>
		}
    </div>
</div>

@helper RenderManufacturer(ManufacturerBriefInfoModel item)
{
    var url = Url.RouteUrl("Manufacturer", new { SeName = item.SeName });

    <article class="art" data-id="@item.Id">
        
        @if (item.PictureUrl.HasValue() && Model.DisplayImages)
        {
            <div class="art-picture-block">
                <a class="art-picture img-center-container" href="@url" title="@item.Name">
                    <img src="@item.PictureUrl" alt="@item.Name" />
                </a>
            </div>
        }
                
        <div class="art-genericname">
            <a href="@url" title="@item.Name">
                <span @Html.LanguageAttributes(item.Name)>@item.Name</span>
            </a>
        </div>
    </article>
}

src/Presentation/SmartStore.Web/Views/Catalog/Partials/HomepageProducts.cshtml
@model ProductSummaryModel
@using SmartStore.Web.Models.Catalog;

@{ 
	if (Model.PagedList.TotalCount == 0)
	{
		return;
	}
}

<div class="product-grid product-grid-home-page block">
	<div class="heading heading-center">
		<h3 class="heading-title fs-h1">@T("HomePage.Products")</h3>
	</div>

    <div class="block-body pt-3 artlist-no-separators">
		@{ 
			Html.RenderPartial("Product.List", Model);
		}
    </div>
</div>

src/Presentation/SmartStore.Web/Views/Catalog/Partials/OffCanvasCompare.cshtml
@model ProductSummaryModel

@using SmartStore.Web.Models.Catalog;

<div class="offcanvas-cart-body offcanvas-scrollable">
    @if (Model.Items.Count == 0)
    {
        <div class="no-items">
            <h4 class="no-item-title">
                @T("ShoppingCart.Mini.EmptyCompare.Title")
            </h4>
            <p class="no-item-icon">
                <i class="fa fa-retweet fa-4x"></i>
            </p>
            <p class="no-item-info text-muted">
                @T("ShoppingCart.Mini.EmptyCompare.Info", "fa fa-lg fa-retweet")
            </p>
        </div>
    }

    @if (Model.Items.Count > 0)
    {
        <div class="offcanvas-cart-items">
            @foreach (var item in Model.Items)
            {
                <div class="offcanvas-cart-item">
                    <div class="row sm-gutters">
                        <div class="col col-alpha">
                            @if (item.Picture.ImageUrl.HasValue())
                            {
                                <a class="img-center-container" href="@Url.RouteUrl("Product", new { SeName = item.SeName })" title="@item.Picture.Title">
                                    <img alt="@item.Picture.AlternateText" src="@item.Picture.ImageUrl" title="@item.Picture.Title" />
                                </a>
                            }
                        </div>

                        <div class="col col-data">
                            <a class="name font-weight-medium" href="@Url.RouteUrl("Product", new { SeName = item.SeName })" title="@item.Name">
								<span @Html.LanguageAttributes(item.Name)>@item.Name</span>
							</a>
							@if (item.ShortDescription.HasValue() == true)
							{
								<div @Html.LanguageAttributes(item.ShortDescription) class="short-desc text-muted">
									@Html.Raw(item.ShortDescription.Value.Truncate(120, "..."))
								</div>
							}

                            <div class="d-flex align-items-center sm-gutters mt-2">
                                <div class="col">
                                    <span class="price unit-price">
                                        @item.Price.Price
                                    </span>
                                </div>
                                <div class="col-auto text-nowrap">
                                    <a class="btn btn-secondary btn-to-danger btn-sm btn-icon remove ajax-cart-link"
                                       href="#"
                                       rel="nofollow"
                                       data-href='@Url.Action("RemoveProductFromCompare", "Catalog", new { id = item.Id })'
                                       data-type="compare"
                                       data-action="remove"
                                       title='@T("Common.Remove")'>
                                        <i class="far fa-trash-alt"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }

            @{ Html.RenderWidget("offcanvas_compare_items_after"); }
        </div>
    }
</div>

@if (Model.Items.Count > 0)
{
    <div class="offcanvas-cart-footer">
        <div class="offcanvas-cart-footer-row sm-gutters">
            <div class="col">
                <a class="btn btn-clear btn-block btn-action" href="@Url.RouteUrl("CompareProducts")">
                    <i class="fa fa-check"></i>
                    <span>@T("Products.Compare.CompareNow")</span>
                </a>
            </div>
            <div class="col">
                <a class="btn btn-clear btn-block btn-action ajax-cart-link" href="#" data-href="@Url.Action("ClearCompareList")" rel="nofollow" data-type="compare" data-action="remove">
                    <i class="fal fa-trash-alt"></i>
                    <span>@T("Products.Compare.Clear")</span>
                </a>
            </div>
        </div>
    </div>
}

src/Presentation/SmartStore.Web/Views/Catalog/Partials/OffCanvasMenu.cshtml
@{ 
	var labelStyle = GetThemeVariable<string>("shopbar-label", "warning");
}

<div class="ocm-home-layer layer show" data-id="0">

    <div class="offcanvas-menu-header offcanvas-tabs">
        <ul class="nav nav-tabs nav-tabs-line row no-gutters" role="tablist">
            @if (ViewBag.ShowCategories == true)
            {
                <li class="nav-item col">
                    <a id="category-tab" class="nav-link" data-toggle="tab" href="#ocm-categories" role="tab" data-initialized="false">
                        <span class="title">@T("Offcanvas.Menu.Categories")</span>
                    </a>
                </li>
            }
            @if (ViewBag.ShowManufacturers == true)
            {
                <li class="nav-item col">
                    <a id="manufacturer-tab" class="nav-link" data-toggle="tab" href="#ocm-manufacturers" role="tab" data-initialized="false">
                        <span class="title">@T("Offcanvas.Menu.Brands")</span>
                    </a>
                </li>
            }
            <li class="nav-item col">
                <a id="service-tab" class="nav-link" data-toggle="tab" href="#ocm-service" role="tab" data-initialized="false">
                    <span class="title">@T("Offcanvas.Menu.Service")</span>
                </a>
            </li>
        </ul>
    </div>

    <div class="tab-content offcanvas-scrollable">
		@if (ViewBag.ShowCategories == true)
		{
			<div class="tab-pane fade" id="ocm-categories" role="tabpanel"></div>
		}
        @if (ViewBag.ShowManufacturers == true)
        {
            <div class="tab-pane fade" id="ocm-manufacturers" role="tabpanel"></div>
        }
        <div class="tab-pane fade" id="ocm-service" role="tabpanel"></div>
    </div>

    <div class="offcanvas-menu-footer d-none">
        <div class="row xs-gutters justify-content-around">
            <div id="ocm-currency-selector" class="col d-none">
                <select class="form-control skin" style="width:100%"></select>
            </div>
            <div id="ocm-language-selector" class="col d-none">
                <select class="form-control skin"></select>
            </div>
        </div>
    </div>
</div>

src/Presentation/SmartStore.Web/Views/Catalog/Partials/PopularProductTags.cshtml
@model PopularProductTagsModel
@using SmartStore.Web.Models.Catalog;
@if (Model.Tags.Count > 0)
{
    <div class="block block-popular-tags mb-5">
		<div class="row">
			<div class="col">
				<div class="heading">
					<h3 class="heading-title fs-h1">
						@T("Products.Tags.Popular")
					</h3>
				</div>
			</div>
			@if (Model.TotalTags > Model.Tags.Count)
			{
				<div class="col col-auto">
					<a class="btn btn-outline-info btn-flat" href="@Url.RouteUrl("ProductTagsAll")">
						<span>@T("Products.Tags.Popular.ViewAll")</span>
						<i class="fa fa-angle-right"></i>
					</a>
				</div>
			}

		</div>

        <div class="listbox block-body">
            <div class="tags fs-h4">
                <ul class="list-inline">
                    @foreach (var item in Model.Tags)
                    {
                        <li class="list-inline-item">
                            <a class="color-body" href="@Url.RouteUrl("ProductsByTag", new { productTagId = item.Id, path = item.SeName })" style="font-size:@(Model.GetFontSize(item))%;">
								<span @Html.LanguageAttributes(item.Name)>@item.Name</span>
							</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
}