src/Presentation/SmartStore.Web/Models/Customer/AccountActivationModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class AccountActivationModel : ModelBase
    {
        public string Result { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/BackInStockSubscriptionModel.cs
using SmartStore.Services.Localization;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class BackInStockSubscriptionModel : EntityModelBase
    {
        public int ProductId { get; set; }
        public LocalizedValue<string> ProductName { get; set; }
        public string SeName { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/ChangePasswordModel.cs
using System.ComponentModel.DataAnnotations;
using FluentValidation;
using FluentValidation.Attributes;
using SmartStore.Core.Domain.Customers;
using SmartStore.Core.Localization;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
	[Validator(typeof(ChangePasswordValidator))]
    public partial class ChangePasswordModel : ModelBase
    {
        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.OldPassword")]
        public string OldPassword { get; set; }

        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.NewPassword")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.ConfirmNewPassword")]
        public string ConfirmNewPassword { get; set; }

        public string Result { get; set; }
    }

    public class ChangePasswordValidator : AbstractValidator<ChangePasswordModel>
    {
        public ChangePasswordValidator(Localizer T, CustomerSettings customerSettings)
        {
            RuleFor(x => x.OldPassword).NotEmpty();
            RuleFor(x => x.NewPassword).NotEmpty();
            RuleFor(x => x.ConfirmNewPassword).NotEmpty();
            RuleFor(x => x.NewPassword).Length(customerSettings.PasswordMinLength, 999);

            RuleFor(x => x.ConfirmNewPassword).Equal(x => x.NewPassword).WithMessage(T("Account.ChangePassword.Fields.NewPassword.EnteredPasswordsDoNotMatch"));
        }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerAddressEditModel.cs
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Models.Common;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerAddressEditModel : ModelBase
    {
        public CustomerAddressEditModel()
        {
            this.Address = new AddressModel();
        }
        public AddressModel Address { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerAddressListModel.cs
using System.Collections.Generic;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Models.Common;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerAddressListModel : ModelBase
    {
        public CustomerAddressListModel()
        {
            Addresses = new List<AddressModel>();
        }

        public IList<AddressModel> Addresses { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerAvatarModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerAvatarModel : ModelBase
    {
        public bool Large { get; set; }
        public string PictureUrl { get; set; }
        public string LinkUrl { get; set; }
        public string AvatarColor { get; set; }
        public char AvatarLetter { get; set; }
        public string UserName { get; set; }
    }

    public partial class CustomerAvatarEditModel : ModelBase
    {
		public string MaxFileSize { get; set; }
        public CustomerAvatarModel Avatar { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerBackInStockSubscriptionsModel.cs
using System.Collections.Generic;
using SmartStore.Core;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerBackInStockSubscriptionsModel : PagedListBase
    {
        public CustomerBackInStockSubscriptionsModel(IPageable pageable) : base(pageable)
        {
            this.Subscriptions = new List<BackInStockSubscriptionModel>();
        }

        public IList<BackInStockSubscriptionModel> Subscriptions { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerDownloadableProductsModel.cs
using System;
using System.Collections.Generic;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Services.Localization;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerDownloadableProductsModel : ModelBase
    {
        public CustomerDownloadableProductsModel()
        {
            Items = new List<DownloadableProductsModel>();
        }

        public IList<DownloadableProductsModel> Items { get; set; }

        #region Nested classes

        public partial class DownloadableProductsModel : ModelBase
        {
            public DownloadableProductsModel()
            {
                DownloadVersions = new List<DownloadVersion>();
            }

            public Guid OrderItemGuid { get; set; }

            public int OrderId { get; set; }

            public int ProductId { get; set; }
            public LocalizedValue<string> ProductName { get; set; }
            public string ProductSeName { get; set; }
			public string ProductUrl { get; set; }
            public string ProductAttributes { get; set; }

            public int LicenseId { get; set; }
            public bool IsDownloadAllowed { get; set; }

            public DateTime CreatedOn { get; set; }

            public List<DownloadVersion> DownloadVersions { get; set; }
        }

        #endregion
    }

    public partial class UserAgreementModel : ModelBase
    {
        public Guid OrderItemGuid { get; set; }
        public string UserAgreementText { get; set; }
        public string FileVersion { get; set; }
    }

    public class DownloadVersion
    {
        public int DownloadId { get; set; }
        public string FileName { get; set; }
        public Guid DownloadGuid { get; set; }
        public string FileVersion { get; set; }
        public string Changelog { get; set; }
    }

}

src/Presentation/SmartStore.Web/Controllers/CountryController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using SmartStore.Core;
using SmartStore.Core.Caching;
using SmartStore.Services.Directory;
using SmartStore.Services.Localization;
using SmartStore.Web.Infrastructure.Cache;
using SmartStore.Web.Framework.Controllers;

namespace SmartStore.Web.Controllers
{
    public partial class CountryController : PublicControllerBase
	{
		#region Fields

        private readonly ICountryService _countryService;
        private readonly IStateProvinceService _stateProvinceService;
        private readonly ILocalizationService _localizationService;
        private readonly IWorkContext _workContext;
        private readonly ICacheManager _cacheManager;

	    #endregion

		#region Constructors

        public CountryController(ICountryService countryService, 
            IStateProvinceService stateProvinceService, 
            ILocalizationService localizationService, 
            IWorkContext workContext,
            ICacheManager cacheManager)
		{
            this._countryService = countryService;
            this._stateProvinceService = stateProvinceService;
            this._localizationService = localizationService;
            this._workContext = workContext;
            this._cacheManager = cacheManager;
		}

        #endregion

        #region States / provinces

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult GetStatesByCountryId(string countryId, bool addEmptyStateIfRequired)
        {
            //this action method gets called via an ajax request
            if (String.IsNullOrEmpty(countryId))
                throw new ArgumentNullException("countryId");

            string cacheKey = string.Format(ModelCacheEventConsumer.STATEPROVINCES_BY_COUNTRY_MODEL_KEY, countryId, addEmptyStateIfRequired, _workContext.WorkingLanguage.Id);
            var cacheModel = _cacheManager.Get(cacheKey, () =>
            {
                var country = _countryService.GetCountryById(Convert.ToInt32(countryId));
                var states = _stateProvinceService.GetStateProvincesByCountryId(country != null ? country.Id : 0).ToList();
                var result = (from s in states
                              select new { id = s.Id, name = s.GetLocalized(x => x.Name).Value })
                              .ToList();

                if (addEmptyStateIfRequired && result.Count == 0)
                    result.Insert(0, new { id = 0, name = _localizationService.GetResource("Address.OtherNonUS") });
                return result;

            });

            return Json(cacheModel, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

src/Presentation/SmartStore.Web/Controllers/DownloadController.cs
using System;
using System.Web;
using System.Web.Mvc;
using SmartStore.Core;
using SmartStore.Core.Domain.Catalog;
using SmartStore.Core.Domain.Customers;
using SmartStore.Core.Domain.Media;
using SmartStore.Core.Html;
using SmartStore.Services.Catalog;
using SmartStore.Services.Media;
using SmartStore.Services.Orders;
using SmartStore.Web.Framework.Controllers;
using System.Linq;

namespace SmartStore.Web.Controllers
{
	public partial class DownloadController : PublicControllerBase
	{
		private readonly IDownloadService _downloadService;
		private readonly IProductService _productService;
		private readonly IOrderService _orderService;
		private readonly IWorkContext _workContext;

		private readonly CustomerSettings _customerSettings;

		public DownloadController(
			IDownloadService downloadService,
			IProductService productService,
			IOrderService orderService,
			IWorkContext workContext,
			CustomerSettings customerSettings)
		{
			this._downloadService = downloadService;
			this._productService = productService;
			this._orderService = orderService;
			this._workContext = workContext;
			this._customerSettings = customerSettings;
		}

		private ActionResult GetFileContentResultFor(Download download, Product product, byte[] data)
		{
			if (data == null || data.LongLength == 0)
            {
                NotifyError(T("Common.Download.NoDataAvailable"));   
                return new RedirectResult(Url.Action("Info", "Customer"));
            }
            
			var fileName = (download.Filename.HasValue() ? download.Filename : download.Id.ToString());
			var contentType = (download.ContentType.HasValue() ? download.ContentType : "application/octet-stream");

			return new FileContentResult(data, contentType)
			{
				FileDownloadName = fileName + download.Extension
			};
		}

		private ActionResult GetFileContentResultFor(Download download, Product product)
		{
			return GetFileContentResultFor(download, product, _downloadService.LoadDownloadBinary(download));
		}
        
		public ActionResult Sample(int productId)
        {
            var product = _productService.GetProductById(productId);
            if (product == null)
				return HttpNotFound();

			if (!product.HasSampleDownload)
            {
                NotifyError(T("Common.Download.HasNoSample"));
                return RedirectToAction("ProductDetails", "Product", new { productId = productId });
            }
            
			var download = _downloadService.GetDownloadById(product.SampleDownloadId.GetValueOrDefault());
            if (download == null)
            {
                NotifyError(T("Common.Download.SampleNotAvailable"));
                return RedirectToAction("ProductDetails", "Product", new { productId = productId });
            }

            if (download.UseDownloadUrl)
                return new RedirectResult(download.DownloadUrl);

			return GetFileContentResultFor(download, product);
        }

		public ActionResult GetDownload(Guid id, bool agree = false, string fileVersion = "")
        {
			if (id == Guid.Empty)
				return HttpNotFound();

			var orderItem = _orderService.GetOrderItemByGuid(id);
            if (orderItem == null)
				return HttpNotFound();

            var order = orderItem.Order;
            var product = orderItem.Product;
            var hasNotification = false;

            if (!_downloadService.IsDownloadAllowed(orderItem))
            {
                hasNotification = true;
                NotifyError(T("Common.Download.NotAllowed"));
            }
            
            if (_customerSettings.DownloadableProductsValidateUser)
            {
                if (_workContext.CurrentCustomer == null)
                    return new HttpUnauthorizedResult();

                if (order.CustomerId != _workContext.CurrentCustomer.Id)
                {
                    hasNotification = true;
                    NotifyError(T("Account.CustomerOrders.NotYourOrder"));
                }
            }

			Download download;

            if (fileVersion.HasValue())
            {
                download = _downloadService.GetDownloadByVersion(product.Id, "Product", fileVersion);
            }
			else
			{
				download = _downloadService.GetDownloadsFor(product).FirstOrDefault();
			}

            if (download == null)
            {
                hasNotification = true;
                NotifyError(T("Common.Download.NoDataAvailable"));
            }

			if (product.HasUserAgreement && !agree)
            {
                hasNotification = true;
            }

            if (!product.UnlimitedDownloads && orderItem.DownloadCount >= product.MaxNumberOfDownloads)
            {
                hasNotification = true;
                NotifyError(T("Common.Download.MaxNumberReached", product.MaxNumberOfDownloads));
            }
            
            if (hasNotification)
            {
                return RedirectToAction("UserAgreement", "Customer", new { id, fileVersion });
            }
            
            if (download.UseDownloadUrl)
            {
                orderItem.DownloadCount++;
                _orderService.UpdateOrder(order);

                return new RedirectResult(download.DownloadUrl);
            }
            else
            {
				var data = _downloadService.LoadDownloadBinary(download);

				if (data == null || data.LongLength == 0)
                {
                    NotifyError(T("Common.Download.NoDataAvailable"));
                    return RedirectToAction("UserAgreement", "Customer", new { id = id });
                }
                
                orderItem.DownloadCount++;
                _orderService.UpdateOrder(order);

				return GetFileContentResultFor(download, product, data);
            }
        }

		public ActionResult GetLicense(Guid id)
        {
			if (id == Guid.Empty)
				return HttpNotFound();
			
			var orderItem = _orderService.GetOrderItemByGuid(id);
            if (orderItem == null)
				return HttpNotFound();

            var order = orderItem.Order;
            var product = orderItem.Product;

            if (!_downloadService.IsLicenseDownloadAllowed(orderItem))
            {
                NotifyError(T("Common.Download.NotAllowed"));
                return RedirectToAction("DownloadableProducts", "Customer");
            }
                

            if (_customerSettings.DownloadableProductsValidateUser)
            {
                if (_workContext.CurrentCustomer == null)
                    return new HttpUnauthorizedResult();

                if (order.CustomerId != _workContext.CurrentCustomer.Id)
                {
                    NotifyError(T("Account.CustomerOrders.NotYourOrder"));
                    return RedirectToAction("DownloadableProducts", "Customer");
                }
            }

            var download = _downloadService.GetDownloadById(orderItem.LicenseDownloadId.HasValue ? orderItem.LicenseDownloadId.Value : 0);
            if (download == null)
            {
                NotifyError(T("Common.Download.NotAvailable"));
                return RedirectToAction("DownloadableProducts", "Customer");
            }
            
            if (download.UseDownloadUrl)
                return new RedirectResult(download.DownloadUrl);

			return GetFileContentResultFor(download, product);
		}

        public ActionResult GetFileUpload(Guid downloadId)
        {
            var download = _downloadService.GetDownloadByGuid(downloadId);
            if (download == null)
            {
                NotifyError(T("Common.Download.NotAvailable"));
                return RedirectToAction("DownloadableProducts", "Customer");
            }

            if (download.UseDownloadUrl)
                return new RedirectResult(download.DownloadUrl);

			return GetFileContentResultFor(download, null);
		}

		public ActionResult GetUserAgreement(int productId, bool? asPlainText)
		{
			var product = _productService.GetProductById(productId);
			if (product == null)
				return Content(T("Products.NotFound", productId));

			if (!product.IsDownload || !product.HasUserAgreement || product.UserAgreementText.IsEmpty())
				return Content(T("DownloadableProducts.HasNoUserAgreement"));

			if (asPlainText ?? false)
			{
				var agreement = HtmlUtils.ConvertHtmlToPlainText(product.UserAgreementText);
				agreement = HtmlUtils.StripTags(HttpUtility.HtmlDecode(agreement));

				return Content(agreement);
			}

			return Content(product.UserAgreementText);
		}
	}
}

src/Presentation/SmartStore.Web/Views/Customer/AccountActivation.cshtml
@model AccountActivationModel
@using SmartStore.Web.Models.Customer;
@{
    Layout = "_Layout";

    Html.AddTitleParts(T("PageTitle.AccountActivation").Text);
}

<div class="page account-activation-page">
    <div class="page-title">
        <h1>@T("Account.AccountActivation")</h1>
    </div>
    <div class="page-body">
        <strong>@Model.Result</strong>
    </div>
</div>

src/Presentation/SmartStore.Web/Views/Customer/AddressEdit.cshtml
@model CustomerAddressEditModel

@using SmartStore.Web.Models.Customer;

@{
	Html.AddTitleParts(T("PageTitle.Account").Text);

	Layout = "_MyAccount";
	ViewBag.PageClassToken = "addresses";
	ViewBag.PageTitle = T("Account.CustomerAddresses.Edit").Text;
}

@using (Html.BeginForm())
{
	var dataDictAddress = new ViewDataDictionary();
	dataDictAddress["breakpoint"] = "lg";
	// Merge ModelState (required for validation)
	dataDictAddress.ModelState.Merge(ViewData.ModelState);
	dataDictAddress.TemplateInfo.HtmlFieldPrefix = "Address";
	Html.RenderPartial("_CreateOrUpdateAddress", Model.Address, dataDictAddress);

	<div class="form-group row">
		<div class="col">
			<button type="submit" class="btn btn-primary btn-lg save-address-button">
				<i class="fa fa-check"></i>
				<span>@T("Common.Save")</span>
			</button>
		</div>
	</div>
}

src/Presentation/SmartStore.Web/Views/Customer/Addresses.cshtml
@model CustomerAddressListModel

@using SmartStore.Web.Models.Customer;
@using SmartStore.Services.Directory;

@{
	Html.AddTitleParts(T("PageTitle.Account").Text);

	Layout = "_MyAccount";
	ViewBag.PageClassToken = "addresses";
	ViewBag.PageTitle = T("Account.CustomerAddresses").Text;
}

@if (Model.Addresses.Count == 0)
{
	<div class="alert alert-warning">@T("Account.CustomerAddresses.NoAddresses")</div>
}

<div class="add-address">
	<a class="btn btn-primary btn-lg add-address-button mb-4" href="@Url.Action("AddressAdd")" rel="nofollow">
		<i class="fa fa-plus"></i>
		<span>@T("Common.AddNew")</span>
	</a>
</div>

@if (Model.Addresses.Count == 0)
{
	return;
}

<div class="card-deck card-cols-sm-1 card-cols-lg-2 address-list">
    @for (int i = 0; i < Model.Addresses.Count; i++)
    {
        var address = Model.Addresses[i];
                    
        <div class="card shadow-sm address-list-item">
            <div class="card-body">
				<h4 class="card-title">@address.GetFormattedName()</h4>

				<div class="mb-2">
					<div class="email">
						@Html.LabelFor(model => model.Addresses[i].Email, new { @class = "m-0" }):
						@address.Email
					</div>
					@if (address.PhoneEnabled)
					{
						<div class="phone">
							@Html.LabelFor(model => model.Addresses[i].PhoneNumber, new { @class = "m-0" }):
							@address.PhoneNumber
						</div>
					}
					@if (address.FaxEnabled && address.FaxNumber.HasValue())
					{
						<div class="fax">
							@Html.LabelFor(model => model.Addresses[i].FaxNumber, new { @class = "m-0" }):
							@address.FaxNumber
						</div>
					}
				</div>

				<div>
					@Html.Raw(address.FormattedAddress)
				</div>
            </div>
                
			<div class="card-footer d-flex p-0">
                <a class="btn btn-secondary btn-lg btn-flat rounded-0 edit-address-button" href="@Url.Action("AddressEdit", new { id = address.Id })">
					<span>@T("Common.Edit")</span>
				</a>
                <a class="btn btn-danger btn-lg btn-flat rounded-0 delete-address-button" href="@Url.Action("AddressDelete", new { id = address.Id })" onclick='return confirm(@T("Common.AreYouSure").JsText);'>
					<span>@T("Common.Delete")</span>
				</a>
            </div>
        </div>
    }
</div>

src/Presentation/SmartStore.Web/Views/Customer/Avatar.cshtml
@using SmartStore.Web.Models.Customer;
@using SmartStore.Web.Framework.UI;
@model CustomerAvatarEditModel
@{
	Layout = "_MyAccount";
	ViewBag.PageClassToken = "avatar";
	ViewBag.PageTitle = T("Account.Avatar").Text;

	Html.AddTitleParts(T("PageTitle.Account").Text);
}

@if (!ViewData.ModelState.IsValid)
{
	@Html.ValidationSummary(true)
}

<div id="AvatarUploadContainer">
	<div class="mb-2">
        @{ Html.RenderPartial("Customer.Avatar", Model.Avatar); }
	</div>

	@(Html.SmartStore().FileUploader()
		.Name("uploadedFile")
		.UploadUrl(Url.Action("UploadAvatar", "Customer"))
		.AcceptedFileTypes("gif|jpe?g|png")
		.ShowRemoveButton(Model.Avatar.PictureUrl.HasValue())
		.ShowRemoveButtonAfterUpload(true)
		.UploadText(T("Common.FileUploader.Upload"))
		.OnUploadCompletedHandlerName("onAvatarUploaded")
		.OnFileRemoveHandlerName("onAvatarRemoved")
	)

	@if (!Model.Avatar.PictureUrl.HasValue())
	{
		<div class="alert alert-info mt-2">@T("Account.Avatar.UploadRules", Model.MaxFileSize)</div>
	}
</div>

<script>
	window['onAvatarUploaded'] = function (e, el, data) {
		var result = data.result;
		if (result.success) {
            window.location = '@Url.Action("Avatar", "Customer", new { area = "" })';
		}
	};

    window['onAvatarRemoved'] = function (e, el) {
		$(this).doPostData({
			url: '@Url.Action("RemoveAvatar", "Customer", new { area = "" })'
		});
	}
</script>

src/Presentation/SmartStore.Web/Views/Customer/DownloadableProducts.cshtml
@model CustomerDownloadableProductsModel

@using SmartStore.Web.Models.Customer;

@{
	Html.AddTitleParts(T("PageTitle.Account").Text);

	Layout = "_MyAccount";
	ViewBag.PageClassToken = "downloads";
	ViewBag.PageTitle = T("Account.DownloadableProducts").Text;
}

@if (Model.Items.Count == 0)
{
	<div class="alert alert-warning">
		@T("DownloadableProducts.NoItems")
	</div>
	return;
}

<div class="card-deck card-cols-sm-1 esd-list">
	@foreach (var item in Model.Items)
	{
		<div class="card shadow-sm esd-item">
			<div class="card-body">
				<h4 class="card-title mb-4" @Html.LanguageAttributes(item.ProductName)>@item.ProductName.Value.Truncate(50, "...")</h4>
				<dl class="row mb-0">
					<dt class="col-sm-3 font-weight-400 text-muted">@T("Order.Order#")</dt>
					<dd class="col-sm-9"><a href="@Url.Action("Details", "Order", new { id = item.OrderId })" rel="nofollow">@item.OrderId</a></dd>
					<dt class="col-sm-3 font-weight-400 text-muted">@T("Common.CreatedOn")</dt>
					<dd class="col-sm-9">@item.CreatedOn.ToNativeString("d")</dd>
					<dt class="col-sm-3 font-weight-400 text-muted">@T("DownloadableProducts.Fields.Product")</dt>
					<dd class="col-sm-9">
						<a href="@item.ProductUrl" title="@T("Products.Details")" @Html.LanguageAttributes(item.ProductName)>@item.ProductName</a>
						@if (item.ProductAttributes.HasValue())
						{
							<div>
								@Html.Raw(item.ProductAttributes)
							</div>
						}
					</dd>
				</dl>
			</div>

			@if (item.IsDownloadAllowed || item.LicenseId > 0)
            {
                <div class="card-footer p-0">
                    <div class="d-flex">
                        @if (item.IsDownloadAllowed)
                        {
                            <a class="btn btn-secondary btn-flat rounded-0" href="@Url.Action("GetDownload", "Download", new { id = item.OrderItemGuid })" rel="nofollow">
                                <i class="fa fa-download"></i>
                                <span>@T("DownloadableProducts.Fields.Download")</span>
                            </a>

                            if (item.DownloadVersions.Count > 1)
                            {
                                <a class="btn btn-secondary btn-flat rounded-0" data-toggle="collapse" href="#download-versions-@item.OrderId" rel="nofollow">
                                    <i class="fa fa-info"></i>
                                    <span>@T("Common.Download.Versions")</span>
                                </a>
                            }
                        }
                        else
                        {
                            <a class="btn btn-secondary btn-flat rounded-0 disabled" href="javascript:void(0)" rel="nofollow">
                                <span>@T("DownloadableProducts.Fields.Download.NA")</span>
                            </a>
                        }

                        @if (item.LicenseId > 0)
                        {
                            <a class="btn btn-secondary btn-flat rounded-0" href="@Url.Action("GetLicense", "Download", new { id = item.OrderItemGuid })" rel="nofollow">
                                <span>@T("DownloadableProducts.Fields.DownloadLicense")</span>
                            </a>
                        }
                    </div>
                </div>

                if (item.IsDownloadAllowed && item.DownloadVersions.Count > 1)
                {
                    <div class="collapse download-versions" id="download-versions-@item.OrderId">
                        <table class="table mb-0">
                            <thead>
                                <tr>
                                    <th scope="col"></th>
                                    <th scope="col">#</th>
                                    <th scope="col">@T("Common.Download.Version")</th>
                                </tr>
                            </thead>
                            <tbody id="download-versions">
                                @foreach (var download in item.DownloadVersions)
                                {
                                    <tr data-toggle="collapse" data-target="#download-@download.DownloadId" class="download-version">
                                        <th scope="row">
                                            <i class="fa fa-fw fa-angle-right"></i>
                                        </th>
                                        <td>
                                            @download.FileVersion
                                        </td>
                                        <td>
                                            <a href="@Url.Action("GetDownload", "Download", new { id = item.OrderItemGuid, fileVersion = download.FileVersion })" class="download-link">
                                                @download.FileName
                                            </a>
                                        </td>
                                    </tr>
                                    
                                    <tr id="download-@download.DownloadId" class="download-changelog collapse bg-light">
                                        <td colspan="3">
                                            <div>
                                                @if (download.Changelog.HasValue())
                                                {
                                                    @Html.Raw(download.Changelog)
                                                }
                                                else
                                                {
                                                    @T("Customer.Downloads.NoChangelogAvailable")
                                                }
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>   
                }
            }
		</div>
	}
</div>

<script type="text/javascript">

	$(function () {
        $('.download-versions .download-changelog').on('show.bs.collapse hide.bs.collapse', function (e) {
            var icon = $(e.target).prev().find("i");
            icon.toggleClass("fa-angle-down", e.type == "show");
        });

        $('.download-versions .download-link').on("click", function (e) {
            e.stopPropagation();
        });
	});

</script>

src/Presentation/SmartStore.Web/Views/Customer/RegisterResult.cshtml
@model RegisterResultModel

@using SmartStore.Web.Models.Customer;

@{
    Layout = "_Layout";

    Html.AddTitleParts(T("PageTitle.Register").Text);

    //continue URL
    var continueUrl = "";
    if (!String.IsNullOrEmpty(this.Context.Request.QueryString["returnUrl"]))
    {
        continueUrl = this.Context.Request.QueryString["returnUrl"];
    }
    else
    {
        continueUrl = Url.RouteUrl("HomePage");
    }
}

<div class="page registration-result-page">
    <div class="page-title">
        <h1>@T("Account.Register")</h1>
    </div>

    <div class="page-body">        
        <p class="section-body">
            @Model.Result
        </p>

        <div class="buttons">
            <a class="btn btn-secondary register-continue-button" href="@continueUrl">
                @T("Account.Register.Result.Continue")
            </a>
        </div>
    </div>
</div>